apiVersion: v1
kind: Service
metadata:
  name: cea-docs-service
  labels:
    app: docs-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: docs
  type: LoadBalancer
